Actividad práctica 2: calculadora de calificaciones escolares con TensorFlow

Objetivo: Aplicar operaciones con TensorFlow para simular un proceso educativo simple.

Alcance: Introducir tensores y operaciones básicas.

Producto final: Notebook funcional con cálculo de promedios usando TensorFlow.


In [ ]:
# Paso 1: Importar TensorFlow
import tensorflow as tf

# Paso 2: Declarar tensores con calificaciones parciales (3 actividades por estudiante)
# Simularemos 5 estudiantes
calificaciones = tf.constant([
    [85.0, 90.0, 78.0],  # Estudiante 1
    [88.0, 92.0, 84.0],  # Estudiante 2
    [75.0, 70.0, 80.0],  # Estudiante 3
    [95.0, 94.0, 96.0],  # Estudiante 4
    [60.0, 65.0, 58.0],  # Estudiante 5
], dtype=tf.float32)
print("Calificaciones parciales (3 actividades por estudiante):")
print(calificaciones)

# Paso 3: Calcular el promedio simple por estudiante usando tf.reduce_mean
promedios = tf.reduce_mean(calificaciones, axis=1)
print("\nPromedio por estudiante:")
print(promedios)

# Paso 4: Calcular nota final ponderada
# Supongamos que: A1 = 30%, A2 = 30%, A3 = 40%
ponderaciones = tf.constant([0.3, 0.3, 0.4], dtype=tf.float32)
notas_finales = tf.reduce_sum(calificaciones * ponderaciones, axis=1)
print("\nNota final por estudiante (ponderada):")
print(notas_finales)

# Paso 5: Evaluar quién aprueba (nota final >= 70)
aprobados = notas_finales >= 70
print("\n¿Aprobado? (True = aprobado, False = reprobado):")
print(aprobados)

# Paso 6: Mostrar resultados finales por estudiante
nombres = ["Estudiante 1", "Estudiante 2", "Estudiante 3", "Estudiante 4", "Estudiante 5"]
for i in range(len(nombres)):
    estado = "Aprobado" if aprobados[i].numpy() else "Reprobado"
    print(f"{nombres[i]}: Nota Final = {notas_finales[i].numpy():.2f} --> {estado}")


Calificaciones parciales (3 actividades por estudiante):
tf.Tensor(
[[85. 90. 78.]
 [88. 92. 84.]
 [75. 70. 80.]
 [95. 94. 96.]
 [60. 65. 58.]], shape=(5, 3), dtype=float32)

Promedio por estudiante:
tf.Tensor([84.333336 88.       75.       95.       61.      ], shape=(5,), dtype=float32)

Nota final por estudiante (ponderada):
tf.Tensor([83.700005 87.600006 75.5      95.100006 60.7     ], shape=(5,), dtype=float32)

¿Aprobado? (True = aprobado, False = reprobado):
tf.Tensor([ True  True  True  True False], shape=(5,), dtype=bool)
Estudiante 1: Nota Final = 83.70 --> Aprobado
Estudiante 2: Nota Final = 87.60 --> Aprobado
Estudiante 3: Nota Final = 75.50 --> Aprobado
Estudiante 4: Nota Final = 95.10 --> Aprobado
Estudiante 5: Nota Final = 60.70 --> Reprobado
